# Docker Compose override for development with reverse proxy testing
# This file extends docker-compose.yml for testing reverse proxy configuration
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.proxy-test.yml up

version: '3.8'

services:
  web-app:
    environment:
      # Override to enable HTTPS-related settings for reverse proxy testing
      SECURE_COOKIES: "true"
      PREFERRED_URL_SCHEME: "https"
      FLASK_DEBUG: "true"  # Keep debug mode for development
      
      # Add these variables to force ProxyFix to use specific settings
      # Useful for testing even without actual proxy headers
      PROXY_FIX_FOR: "1"
      PROXY_FIX_PROTO: "1" 
      PROXY_FIX_HOST: "1"
      PROXY_FIX_PORT: "1"
      PROXY_FIX_PREFIX: "1"
