version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_proxy_params:/etc/nginx/proxy_params:ro
      - ./logs/nginx:/var/log/nginx
      - static_files:/var/www/static:ro
    depends_on:
      - web-app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  web-app:
    image: justinkumpe/mercury-bank-sync-gui:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      # Performance optimizations
      - ENABLE_COMPRESSION=true
      - STATIC_FILE_CACHING=true
      - DB_POOL_SIZE=20
      - DB_POOL_RECYCLE=3600
      - WERKZEUG_RUN_MAIN=true
    volumes:
      - static_files:/app/static
      - ./logs/web:/app/logs
    depends_on:
      - db
      - sync-app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  sync-app:
    image: justinkumpe/mercury-bank-sync:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MERCURY_API_URL=${MERCURY_API_URL}
      - MERCURY_SANDBOX_MODE=${MERCURY_SANDBOX_MODE}
      - SYNC_INTERVAL_MINUTES=${SYNC_INTERVAL_MINUTES:-60}
      - SYNC_DAYS_BACK=${SYNC_DAYS_BACK:-30}
      - PYTHONUNBUFFERED=1
      # Performance optimizations
      - DB_POOL_SIZE=10
      - DB_POOL_RECYCLE=3600
    volumes:
      - ./logs/sync:/app/logs
    depends_on:
      - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "python", "health_check.py"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-mercury_bank}
      - MYSQL_USER=${MYSQL_USER:-mercury}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./logs/mysql:/var/log/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    command: >
      --innodb-buffer-pool-size=256M
      --innodb-log-file-size=64M
      --innodb-flush-log-at-trx-commit=2
      --innodb-flush-method=O_DIRECT
      --query-cache-type=1
      --query-cache-size=64M
      --slow-query-log=1
      --slow-query-log-file=/var/log/mysql/slow.log
      --long-query-time=2
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=hydra
    depends_on:
      - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

volumes:
  mysql_data:
    driver: local
  static_files:
    driver: local

networks:
  default:
    driver: bridge
