services:
  # Mercury sync service
  mercury-sync:
    build: ./sync_app
    image: "mercury_bank_sync:dev"
    environment:
      # Database configuration
      - DATABASE_URL=mysql+pymysql://Bot_mercury:LetmeN2it@172.16.21.10:3306/Bot_mercury
      - MERCURY_SANDBOX_MODE=true
      
      # Sync configuration
      - SYNC_DAYS_BACK=30
      - SYNC_INTERVAL_MINUTES=2
      - RUN_ONCE=false
    
    volumes:
      - ./sync_app/logs:/app/logs
    
    restart: unless-stopped
    
    networks:
      - mercury-network

  # Web application service
  web-app:
    build: ./web_app
    image: "mercury_bank_sync_gui:dev"
    environment:
      - DATABASE_URL=mysql+pymysql://Bot_mercury:LetmeN2it@172.16.21.10:3306/Bot_mercury
      - SECRET_KEY=dev-secret-key-change-this
    
    ports:
      - "5001:5000"
    
    volumes:
      - ./web_app/logs:/app/logs
    
    restart: unless-stopped
    
    networks:
      - mercury-network

  # Database admin interface
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - mercury-network

networks:
  mercury-network:
    driver: bridge
