x-common-variables: &common-variables
   DATABASE_URL: mysql+pymysql://user:password@server:3306/Database
   SYNC_DAYS_BACK: 30
   SYNC_INTERVAL_MINUTES: 2
   RUN_ONCE: false
   SECRET_KEY: change-this-secret-key-for-production

services:
  mercury-sync:
    image: "justinkumpe/mercury-bank-sync:latest-beta"
    # Uncomment below for local development
    # build: ./sync_app
    environment: *common-variables
    
    volumes:
      - ./sync_app/logs:/app/logs
    
    restart: unless-stopped
    
    networks:
      - mercury-network

  # Web application service
  web-app:
    image: "justinkumpe/mercury-bank-sync-gui:latest-beta"
    # Uncomment below for local development
    # build: ./web_app
    environment: *common-variables
    
    ports:
      - "5001:5000"
    
    volumes:
      - ./web_app/logs:/app/logs
    
    restart: unless-stopped
    
    networks:
      - mercury-network
    
    depends_on:
      - mercury-sync

  # Database admin interface
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - mercury-network

networks:
  mercury-network:
    driver: bridge
