"""Add name field and multi-account support to transaction restrictions

Revision ID: e7f6f63389a5
Revises: 461b38475b9e
Create Date: 2025-07-25 23:11:48.862060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f6f63389a5'
down_revision: Union[str, Sequence[str], None] = '461b38475b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_accounts_exclude_reports'), table_name='accounts')
    op.drop_index(op.f('idx_accounts_mercury_account_id'), table_name='accounts')
    op.drop_index(op.f('idx_accounts_name'), table_name='accounts')
    op.drop_index(op.f('idx_budget_categories_budget_id'), table_name='budget_categories')
    op.drop_index(op.f('idx_budgets_budget_month'), table_name='budgets')
    op.drop_index(op.f('idx_budgets_is_active'), table_name='budgets')
    op.drop_index(op.f('idx_budgets_mercury_account_id'), table_name='budgets')
    op.drop_index(op.f('idx_mercury_accounts_is_active'), table_name='mercury_accounts')
    op.drop_index(op.f('idx_mercury_accounts_name'), table_name='mercury_accounts')
    op.drop_index(op.f('idx_mercury_accounts_sync_enabled'), table_name='mercury_accounts')
    op.drop_index(op.f('idx_notification_logs_created_at'), table_name='notification_logs')
    op.drop_index(op.f('idx_notification_logs_notification_type'), table_name='notification_logs')
    op.drop_index(op.f('idx_notification_logs_recipient_type'), table_name='notification_logs')
    op.drop_index(op.f('idx_notification_logs_status'), table_name='notification_logs')
    op.drop_index(op.f('idx_transaction_approval_logs_approval_id'), table_name='transaction_approval_logs')
    op.drop_index(op.f('idx_transaction_approval_logs_transaction_id'), table_name='transaction_approval_logs')
    op.drop_index(op.f('idx_transaction_approval_logs_used_at'), table_name='transaction_approval_logs')
    op.drop_index(op.f('idx_transaction_approval_requests_approval_end_date'), table_name='transaction_approval_requests')
    op.drop_index(op.f('idx_transaction_approval_requests_approval_start_date'), table_name='transaction_approval_requests')
    op.drop_index(op.f('idx_transaction_approval_requests_requested_by_user_id'), table_name='transaction_approval_requests')
    op.drop_index(op.f('idx_transaction_approval_requests_restriction_id'), table_name='transaction_approval_requests')
    op.drop_index(op.f('idx_transaction_approval_requests_status'), table_name='transaction_approval_requests')
    op.drop_index(op.f('idx_transaction_approval_rules_account_id'), table_name='transaction_approval_rules')
    op.drop_index(op.f('idx_transaction_approval_rules_is_active'), table_name='transaction_approval_rules')
    op.drop_index(op.f('idx_transaction_approval_rules_mercury_account_id'), table_name='transaction_approval_rules')
    op.drop_index(op.f('idx_transaction_approval_rules_priority'), table_name='transaction_approval_rules')
    op.drop_index(op.f('idx_transaction_approvals_account_id'), table_name='transaction_approvals')
    op.drop_index(op.f('idx_transaction_approvals_approval_end_date'), table_name='transaction_approvals')
    op.drop_index(op.f('idx_transaction_approvals_approval_start_date'), table_name='transaction_approvals')
    op.drop_index(op.f('idx_transaction_approvals_is_active'), table_name='transaction_approvals')
    op.drop_index(op.f('idx_transaction_approvals_request_id'), table_name='transaction_approvals')
    op.drop_index(op.f('idx_transaction_attachments_transaction_id'), table_name='transaction_attachments')
    op.drop_index(op.f('idx_transaction_restrictions_account_id'), table_name='transaction_restrictions')
    op.drop_index(op.f('idx_transaction_restrictions_end_date'), table_name='transaction_restrictions')
    op.drop_index(op.f('idx_transaction_restrictions_is_active'), table_name='transaction_restrictions')
    op.drop_index(op.f('idx_transaction_restrictions_mercury_account_id'), table_name='transaction_restrictions')
    op.drop_index(op.f('idx_transaction_restrictions_start_date'), table_name='transaction_restrictions')
    op.drop_index(op.f('idx_transactions_account_created'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_account_id'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_account_posted'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_account_posted_amount'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_amount'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_description'), table_name='transactions', mysql_length={'description': 255})
    op.drop_index(op.f('idx_transactions_note'), table_name='transactions', mysql_length={'note': 255})
    op.drop_index(op.f('idx_transactions_note_posted'), table_name='transactions', mysql_length={'note': 100})
    op.drop_index(op.f('idx_transactions_posted_at'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_status'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_status_posted'), table_name='transactions')
    op.drop_index(op.f('idx_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('idx_users_created_at'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('idx_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    op.create_index(op.f('idx_transactions_status_posted'), 'transactions', ['status', 'posted_at'], unique=False)
    op.create_index(op.f('idx_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('idx_transactions_posted_at'), 'transactions', ['posted_at'], unique=False)
    op.create_index(op.f('idx_transactions_note_posted'), 'transactions', ['note', 'posted_at'], unique=False, mysql_length={'note': 100})
    op.create_index(op.f('idx_transactions_note'), 'transactions', ['note'], unique=False, mysql_length={'note': 255})
    op.create_index(op.f('idx_transactions_description'), 'transactions', ['description'], unique=False, mysql_length={'description': 255})
    op.create_index(op.f('idx_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('idx_transactions_amount'), 'transactions', ['amount'], unique=False)
    op.create_index(op.f('idx_transactions_account_posted_amount'), 'transactions', ['account_id', 'posted_at', 'amount'], unique=False)
    op.create_index(op.f('idx_transactions_account_posted'), 'transactions', ['account_id', 'posted_at'], unique=False)
    op.create_index(op.f('idx_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('idx_transactions_account_created'), 'transactions', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_transaction_restrictions_start_date'), 'transaction_restrictions', ['start_date'], unique=False)
    op.create_index(op.f('idx_transaction_restrictions_mercury_account_id'), 'transaction_restrictions', ['mercury_account_id'], unique=False)
    op.create_index(op.f('idx_transaction_restrictions_is_active'), 'transaction_restrictions', ['is_active'], unique=False)
    op.create_index(op.f('idx_transaction_restrictions_end_date'), 'transaction_restrictions', ['end_date'], unique=False)
    op.create_index(op.f('idx_transaction_restrictions_account_id'), 'transaction_restrictions', ['account_id'], unique=False)
    op.create_index(op.f('idx_transaction_attachments_transaction_id'), 'transaction_attachments', ['transaction_id'], unique=False)
    op.create_index(op.f('idx_transaction_approvals_request_id'), 'transaction_approvals', ['request_id'], unique=False)
    op.create_index(op.f('idx_transaction_approvals_is_active'), 'transaction_approvals', ['is_active'], unique=False)
    op.create_index(op.f('idx_transaction_approvals_approval_start_date'), 'transaction_approvals', ['approval_start_date'], unique=False)
    op.create_index(op.f('idx_transaction_approvals_approval_end_date'), 'transaction_approvals', ['approval_end_date'], unique=False)
    op.create_index(op.f('idx_transaction_approvals_account_id'), 'transaction_approvals', ['account_id'], unique=False)
    op.create_index(op.f('idx_transaction_approval_rules_priority'), 'transaction_approval_rules', ['priority'], unique=False)
    op.create_index(op.f('idx_transaction_approval_rules_mercury_account_id'), 'transaction_approval_rules', ['mercury_account_id'], unique=False)
    op.create_index(op.f('idx_transaction_approval_rules_is_active'), 'transaction_approval_rules', ['is_active'], unique=False)
    op.create_index(op.f('idx_transaction_approval_rules_account_id'), 'transaction_approval_rules', ['account_id'], unique=False)
    op.create_index(op.f('idx_transaction_approval_requests_status'), 'transaction_approval_requests', ['status'], unique=False)
    op.create_index(op.f('idx_transaction_approval_requests_restriction_id'), 'transaction_approval_requests', ['restriction_id'], unique=False)
    op.create_index(op.f('idx_transaction_approval_requests_requested_by_user_id'), 'transaction_approval_requests', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('idx_transaction_approval_requests_approval_start_date'), 'transaction_approval_requests', ['approval_start_date'], unique=False)
    op.create_index(op.f('idx_transaction_approval_requests_approval_end_date'), 'transaction_approval_requests', ['approval_end_date'], unique=False)
    op.create_index(op.f('idx_transaction_approval_logs_used_at'), 'transaction_approval_logs', ['used_at'], unique=False)
    op.create_index(op.f('idx_transaction_approval_logs_transaction_id'), 'transaction_approval_logs', ['transaction_id'], unique=False)
    op.create_index(op.f('idx_transaction_approval_logs_approval_id'), 'transaction_approval_logs', ['approval_id'], unique=False)
    op.create_index(op.f('idx_notification_logs_status'), 'notification_logs', ['status'], unique=False)
    op.create_index(op.f('idx_notification_logs_recipient_type'), 'notification_logs', ['recipient_type'], unique=False)
    op.create_index(op.f('idx_notification_logs_notification_type'), 'notification_logs', ['notification_type'], unique=False)
    op.create_index(op.f('idx_notification_logs_created_at'), 'notification_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_mercury_accounts_sync_enabled'), 'mercury_accounts', ['sync_enabled'], unique=False)
    op.create_index(op.f('idx_mercury_accounts_name'), 'mercury_accounts', ['name'], unique=False)
    op.create_index(op.f('idx_mercury_accounts_is_active'), 'mercury_accounts', ['is_active'], unique=False)
    op.create_index(op.f('idx_budgets_mercury_account_id'), 'budgets', ['mercury_account_id'], unique=False)
    op.create_index(op.f('idx_budgets_is_active'), 'budgets', ['is_active'], unique=False)
    op.create_index(op.f('idx_budgets_budget_month'), 'budgets', ['budget_month'], unique=False)
    op.create_index(op.f('idx_budget_categories_budget_id'), 'budget_categories', ['budget_id'], unique=False)
    op.create_index(op.f('idx_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('idx_accounts_mercury_account_id'), 'accounts', ['mercury_account_id'], unique=False)
    op.create_index(op.f('idx_accounts_exclude_reports'), 'accounts', ['exclude_from_reports'], unique=False)
    # ### end Alembic commands ###
