"""Test migration - should detect no changes

Revision ID: ee622ee0f340
Revises: 3af8894c0ebc
Create Date: 2025-07-04 14:12:04.114501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ee622ee0f340'
down_revision: Union[str, Sequence[str], None] = '3af8894c0ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'receipt_required')
    op.drop_column('accounts', 'receipt_threshold')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('receipt_threshold', mysql.FLOAT(), nullable=True))
    op.add_column('accounts', sa.Column('receipt_required', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
