name: Push Sync GUI Service to Docker Hub (Release)

concurrency:
  group: release
  cancel-in-progress: true

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Deploy Image
        run: |
            docker buildx build --push \
                --tag ${{ secrets.DOCKER_USERNAME }}/mercury-bank-sync-gui:${{ github.ref_name }} \
                --platform linux/amd64,linux/arm/v7,linux/arm64 \
                ./web_app
