name: Push Sync Service to Docker Hub (Beta)

concurrency:
  group: sync-beta
  cancel-in-progress: true

on:
  push:
    branches: [dev]
    paths: 
      - 'sync_app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sync-beta
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/mercury-bank-sync
          tags: |
            type=raw,value=latest-beta
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./sync_app
          platforms: linux/amd64  # Beta: single platform for faster development builds
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
